-- SQL Script to Create Tables for Student Attendance System in Supabase

-- 1. Students Table
CREATE TABLE students (
    roll_no TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    department TEXT NOT NULL,
    email TEXT UNIQUE,
    phone_no TEXT,
    enrolled_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Attendance Table
CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_no TEXT NOT NULL REFERENCES students(roll_no) ON DELETE CASCADE,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    department TEXT NOT NULL,
    similarity FLOAT8,
    date DATE NOT NULL DEFAULT (CURRENT_DATE),
    time TIME NOT NULL DEFAULT (CURRENT_TIME),
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- Note: In Supabase SQL Editor, simply paste and run this script.
